apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov
spec:
   template:
      spec:
         containers:
         - name: dov
           resources:
              requests:
                 cpu: "128m"
                 memory: "256Mi"
              limits:
                 cpu: "256m"
                 memory: "512Mi"

