apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../javascript

commonLabels:
   env: dev

namePrefix: dev-

replicas:
- name: dov
  count: 2

images:
- name: dov
  newName: dov-java
  newTag: v3-java

configMapGenerator:
- name: dov
  literals:
  - INSTANCE_NAME="this is friday the 13th"

patchesStrategicMerge:
- ./add_resources.yaml
